#ifndef OLAYER_NATIVE_H
#define OLAYER_NATIVE_H

/* Automatically generated by cbindgen. Do not modify manually. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>
typedef struct TerrainEngine TerrainEngine;
typedef struct InterpolationEngine InterpolationEngine;

/**
 * Conversion constant: 1 Nautical Mile in meters (exact standard).
 */
#define METERS_PER_NAUTICAL_MILE 1852.0

/**
 * Standard Rate-One turn rate in degrees per second ($3^\circ/\text{s}$, $180^\circ$ in 1 minute).
 */
#define STANDARD_RATE_ONE_TURN_DPS 3.0

/**
 * C representation of vertical profile point.
 */
struct C_ProfilePoint {
  double distance_meters;
  double ground_elevation;
  double lat;
  double lon;
  double height;
};

/**
 * C representation of interpolated target.
 */
struct C_InterpolatedTarget {
  char *id;
  double lat;
  double lon;
  double height;
  double heading_rad;
  int quality;
};

/**
 * C representation of topocentric East-North-Up coordinate.
 */
struct C_EnuPoint {
  double east_m;
  double north_m;
  double up_m;
};

/**
 * C representation of geodetic coordinate.
 */
struct C_LatLon {
  double lat;
  double lon;
  double height;
};

/**
 * C representation of magnetic field elements.
 */
struct C_MagneticElements {
  double declination_rad;
  double inclination_rad;
  double horizontal_intensity_nt;
  double total_intensity_nt;
  double x_nt;
  double y_nt;
  double z_nt;
};

/**
 * C representation of route deviation metrics (XTK / ATD).
 */
struct C_RouteDeviation {
  double cross_track_error_meters;
  double along_track_distance_meters;
  struct C_LatLon nearest_point;
};

/**
 * C representation of Range and Bearing Line (RBL / CRSR) measurement.
 */
struct C_RblMeasurement {
  double from_lat_deg;
  double from_lon_deg;
  double to_lat_deg;
  double to_lon_deg;
  double distance_nm;
  double distance_km;
  double true_bearing_deg;
  double magnetic_bearing_deg;
  double reciprocal_true_bearing_deg;
  double reciprocal_magnetic_bearing_deg;
  double estimated_time_enroute_sec;
};

/**
 * C representation of a Projected Position Leader (PPL) tick mark.
 */
struct C_PplTick {
  double time_minutes;
  double distance_nm;
  double lat_deg;
  double lon_deg;
};

/**
 * C representation of a radio navigation aid summary.
 */
struct C_NavaidSummary {
  double lat;
  double lon;
  double elevation_m;
  double frequency_mhz;
  int navaid_type_code;
};

/**
 * Opaque pointer type for SIGMET dataset in C ABI.
 */
typedef SigmetDataset SigmetDataset;

/**
 * Creates a new TerrainEngine instance and returns an opaque pointer.
 */
TerrainEngine *olayer_terrain_engine_create(void);

/**
 * Parses and registers a raw DTED buffer.
 * Returns 0 on success, or a negative code on error.
 */
int olayer_terrain_engine_load_tile(TerrainEngine *engine,
                                    const uint8_t *data,
                                    uintptr_t length,
                                    int32_t *out_lat_deg,
                                    int32_t *out_lon_deg);

/**
 * Unloads a terrain tile. Returns 1 if tile existed, 0 if not, or negative error.
 */
int olayer_terrain_engine_unload_tile(TerrainEngine *engine, int32_t lat_deg, int32_t lon_deg);

/**
 * Loads and registers a Web Mercator (Z, X, Y) RGB elevation tile.
 * encoding_code: 0 = MapboxRgb, 1 = Terrarium.
 * Returns 0 on success, or a negative code on error.
 */
int olayer_terrain_engine_load_rgb_tile(TerrainEngine *engine,
                                        uint32_t z,
                                        uint32_t x,
                                        uint32_t y,
                                        int encoding_code,
                                        const uint8_t *rgba_data,
                                        uintptr_t rgba_len,
                                        uintptr_t width,
                                        uintptr_t height);

/**
 * Loads a GeoTIFF / Cloud-Optimized GeoTIFF raster.
 * Returns 0 on success, or negative error.
 */
int olayer_terrain_engine_load_geotiff(TerrainEngine *engine,
                                       const uint8_t *data,
                                       uintptr_t length,
                                       double *out_min_lat_deg,
                                       double *out_min_lon_deg,
                                       double *out_max_lat_deg,
                                       double *out_max_lon_deg);

/**
 * Decodes Mapbox Terrain-RGB pixel value to elevation in meters.
 */
int olayer_terrain_decode_mapbox_rgb(uint8_t r, uint8_t g, uint8_t b, double *out_elevation);

/**
 * Decodes Mapzen / Nextzen Terrarium RGB pixel value to elevation in meters.
 */
int olayer_terrain_decode_terrarium_rgb(uint8_t r, uint8_t g, uint8_t b, double *out_elevation);

/**
 * Resolves elevation at coordinate degrees. Returns 0 on success, negative error.
 */
int olayer_terrain_engine_get_elevation(TerrainEngine *engine,
                                        double lat_deg,
                                        double lon_deg,
                                        double *out_elevation);

/**
 * Resolves elevation at coordinate radians. Returns 0 on success, negative error.
 */
int olayer_terrain_engine_get_elevation_rad(TerrainEngine *engine,
                                            double lat_rad,
                                            double lon_rad,
                                            double *out_elevation);

/**
 * Resolves elevation at radians while preserving DTED null samples.
 * Returns 0 for valid data, 1 for unknown elevation, or a negative error.
 */
int olayer_terrain_engine_get_elevation_status(TerrainEngine *engine,
                                               double lat_rad,
                                               double lon_rad,
                                               double *out_elevation);

/**
 * Computes MSAW clearance. Returns 0 safe, 1 warning, 2 unknown terrain, or a negative error.
 */
int olayer_terrain_engine_calculate_clearance(TerrainEngine *engine,
                                              double lat_rad,
                                              double lon_rad,
                                              double aircraft_height_meters,
                                              double minimum_clearance_meters,
                                              bool reject_unknown,
                                              double *out_clearance);

/**
 * Generates a vertical profile. Fills out_profile and out_count.
 * Returns 0 on success, negative error.
 */
int olayer_terrain_engine_get_vertical_profile(TerrainEngine *engine,
                                               const double *route_lat,
                                               const double *route_lon,
                                               const double *route_height,
                                               uintptr_t route_len,
                                               double step_meters,
                                               struct C_ProfilePoint **out_profile,
                                               uintptr_t *out_count);

/**
 * Frees profile point array allocated by Rust.
 */
void olayer_profile_points_free(struct C_ProfilePoint *points, uintptr_t count);

/**
 * Sets the terrain tile cache capacity. Returns 0 on success, negative error.
 */
int olayer_terrain_engine_set_cache_capacity(TerrainEngine *engine, uintptr_t capacity);

/**
 * Returns the current number of cached terrain tiles.
 */
uintptr_t olayer_terrain_engine_cache_size(TerrainEngine *engine);

/**
 * Clears all cached terrain tiles.
 */
void olayer_terrain_engine_clear_cache(TerrainEngine *engine);

/**
 * Destroys a TerrainEngine instance.
 */
void olayer_terrain_engine_free(TerrainEngine *engine);

/**
 * Creates a new InterpolationEngine instance.
 */
InterpolationEngine *olayer_interpolator_create(void);

/**
 * Creates a new InterpolationEngine instance with custom stale threshold.
 */
InterpolationEngine *olayer_interpolator_create_with_threshold(double stale_threshold);

/**
 * Updates or inserts a target state. Returns 0 on success, negative error.
 */
int olayer_interpolator_update(InterpolationEngine *engine,
                               const char *id,
                               double lat,
                               double lon,
                               double height,
                               double speed_mps,
                               double track_heading_rad,
                               double vertical_rate_mps,
                               double time);

/**
 * Removes a target. Returns 1 if present, 0 if not, or negative error.
 */
int olayer_interpolator_remove(InterpolationEngine *engine, const char *id);

/**
 * Interpolates all targets. Fills out_targets and out_count.
 * Returns 0 on success, negative error.
 */
int olayer_interpolator_interpolate_all(InterpolationEngine *engine,
                                        double current_time,
                                        struct C_InterpolatedTarget **out_targets,
                                        uintptr_t *out_count);

/**
 * Frees interpolated targets allocated by Rust.
 */
void olayer_interpolated_targets_free(struct C_InterpolatedTarget *targets, uintptr_t count);

/**
 * Destroys an InterpolationEngine instance.
 */
void olayer_interpolator_free(InterpolationEngine *engine);

/**
 * Creates a new `LocalTangentFrame` at the given geodetic origin.
 */
LocalTangentFrame *olayer_local_frame_create(double origin_lat,
                                             double origin_lon,
                                             double origin_height);

/**
 * Converts LLA to local ENU coordinates. Returns 0 on success, negative error.
 */
int olayer_local_frame_lla_to_enu(LocalTangentFrame *frame,
                                  double lat,
                                  double lon,
                                  double height,
                                  struct C_EnuPoint *out_enu);

/**
 * Converts local ENU coordinates to LLA. Returns 0 on success, negative error.
 */
int olayer_local_frame_enu_to_lla(LocalTangentFrame *frame,
                                  double east_m,
                                  double north_m,
                                  double up_m,
                                  struct C_LatLon *out_lla);

/**
 * Calculates radar look angles without atmospheric refraction. Returns 0 on success, negative error.
 */
int olayer_local_frame_radar_look_angles(LocalTangentFrame *frame,
                                         double target_lat,
                                         double target_lon,
                                         double target_height,
                                         double *out_slant_range,
                                         double *out_azimuth_rad,
                                         double *out_elevation_rad);

/**
 * Calculates radar look angles with 4/3 tropospheric refraction. Returns 0 on success, negative error.
 */
int olayer_local_frame_radar_look_angles_refracted(LocalTangentFrame *frame,
                                                   double target_lat,
                                                   double target_lon,
                                                   double target_height,
                                                   double k_factor,
                                                   double *out_slant_range,
                                                   double *out_azimuth_rad,
                                                   double *out_elevation_rad);

/**
 * Destroys a `LocalTangentFrame` instance.
 */
void olayer_local_frame_free(LocalTangentFrame *frame);

/**
 * Creates a default `MagneticModel` instance initialized with built-in WMM-2025.
 */
MagneticModel *olayer_magnetic_model_create_default(void);

/**
 * Creates a `MagneticModel` from a null-terminated `WMM.COF` string.
 * Returns null pointer if parsing fails or string is invalid UTF-8.
 */
MagneticModel *olayer_magnetic_model_create_from_cof(const char *cof_str);

/**
 * Computes magnetic declination using a specific `MagneticModel` instance.
 */
int olayer_magnetic_model_get_declination(MagneticModel *model,
                                          double lat,
                                          double lon,
                                          double height,
                                          double epoch,
                                          double *out_declination_rad);

/**
 * Computes magnetic field elements using a specific `MagneticModel` instance.
 */
int olayer_magnetic_model_get_elements(MagneticModel *model,
                                       double lat,
                                       double lon,
                                       double height,
                                       double epoch,
                                       struct C_MagneticElements *out_elements);

/**
 * Converts True bearing to Magnetic bearing using a specific `MagneticModel` instance.
 */
int olayer_magnetic_model_true_to_magnetic(MagneticModel *model,
                                           double true_bearing_rad,
                                           double lat,
                                           double lon,
                                           double height,
                                           double epoch,
                                           double *out_mag_bearing_rad);

/**
 * Converts Magnetic bearing to True bearing using a specific `MagneticModel` instance.
 */
int olayer_magnetic_model_magnetic_to_true(MagneticModel *model,
                                           double mag_bearing_rad,
                                           double lat,
                                           double lon,
                                           double height,
                                           double epoch,
                                           double *out_true_bearing_rad);

/**
 * Destroys a `MagneticModel` instance.
 */
void olayer_magnetic_model_free(MagneticModel *model);

/**
 * Computes magnetic declination in radians using default WMM-2025. Returns 0 on success, negative error.
 */
int olayer_magnetic_get_declination(double lat,
                                    double lon,
                                    double height,
                                    double epoch,
                                    double *out_declination_rad);

/**
 * Computes all magnetic field elements using default WMM-2025. Returns 0 on success, negative error.
 */
int olayer_magnetic_get_elements(double lat,
                                 double lon,
                                 double height,
                                 double epoch,
                                 struct C_MagneticElements *out_elements);

/**
 * Converts True bearing to Magnetic bearing using default WMM-2025. Returns 0 on success, negative error.
 */
int olayer_magnetic_true_to_magnetic(double true_bearing_rad,
                                     double lat,
                                     double lon,
                                     double height,
                                     double epoch,
                                     double *out_mag_bearing_rad);

/**
 * Converts Magnetic bearing to True bearing using default WMM-2025. Returns 0 on success, negative error.
 */
int olayer_magnetic_magnetic_to_true(double mag_bearing_rad,
                                     double lat,
                                     double lon,
                                     double height,
                                     double epoch,
                                     double *out_true_bearing_rad);

/**
 * Computes route deviation (XTK and ATD). Returns 0 on success, negative error.
 */
int olayer_spatial_compute_route_deviation(struct C_LatLon start,
                                           struct C_LatLon end,
                                           struct C_LatLon pos,
                                           struct C_RouteDeviation *out_deviation);

/**
 * Computes geodesic line-line intersection. Returns 1 if intersects, 0 if disjoint, negative error.
 */
int olayer_spatial_geodesic_intersection(struct C_LatLon p1,
                                         struct C_LatLon p2,
                                         struct C_LatLon p3,
                                         struct C_LatLon p4,
                                         struct C_LatLon *out_intersection);

/**
 * Evaluates spherical polygon point containment. Returns 0 on success, negative error.
 * `*out_contains` is set to 1 if contained, 0 if not.
 */
int olayer_spatial_polygon_contains_point(const struct C_LatLon *poly_coords,
                                          uintptr_t num_coords,
                                          struct C_LatLon point,
                                          int *out_contains);

/**
 * Computes Range and Bearing Line (RBL / CRSR) measurement. Returns 0 on success, negative error.
 */
int olayer_tools_compute_rbl(double from_lat_deg,
                             double from_lon_deg,
                             double to_lat_deg,
                             double to_lon_deg,
                             double speed_knots,
                             double epoch_year,
                             struct C_RblMeasurement *out_measurement);

/**
 * Generates Projected Position Leader (PPL) vector ticks. Returns 0 on success, negative error.
 */
int olayer_tools_generate_ppl(double lat_deg,
                              double lon_deg,
                              double ground_speed_knots,
                              double track_deg,
                              const double *intervals_minutes,
                              uintptr_t num_intervals,
                              struct C_PplTick *out_ticks,
                              uintptr_t max_ticks,
                              uintptr_t *out_ticks_written);

/**
 * Generates racetrack holding pattern polyline coordinates. Returns 0 on success, negative error.
 */
int olayer_tools_generate_holding_pattern(double fix_lat_deg,
                                          double fix_lon_deg,
                                          double inbound_bearing_deg,
                                          int is_standard_right_turn,
                                          double leg_time_minutes,
                                          double airspeed_knots,
                                          uintptr_t points_per_turn,
                                          struct C_LatLon *out_coords,
                                          uintptr_t max_coords,
                                          uintptr_t *out_coords_written);

/**
 * Generates ILS approach funnel polygon coordinates. Returns 0 on success, negative error.
 */
int olayer_tools_generate_ils_cone(double threshold_lat_deg,
                                   double threshold_lon_deg,
                                   double runway_heading_deg,
                                   double length_nm,
                                   double fov_deg,
                                   uintptr_t arc_steps,
                                   struct C_LatLon *out_polygon_coords,
                                   uintptr_t max_polygon_coords,
                                   uintptr_t *out_polygon_coords_written);

/**
 * Generates concentric range rings coordinates. Returns 0 on success, negative error.
 */
int olayer_tools_generate_range_rings(double center_lat_deg,
                                      double center_lon_deg,
                                      double radius_nm,
                                      uintptr_t points_per_ring,
                                      struct C_LatLon *out_ring_coords,
                                      uintptr_t max_coords,
                                      uintptr_t *out_coords_written);

/**
 * Loads an `AeronauticalDataset` from an AIXM 5.1 XML null-terminated UTF-8 string.
 * Returns null pointer on error.
 */
AeronauticalDataset *olayer_aeronautical_dataset_from_aixm(const char *xml_utf8);

/**
 * Loads an `AeronauticalDataset` from a GeoJSON-Aviation null-terminated UTF-8 string.
 * Returns null pointer on error.
 */
AeronauticalDataset *olayer_aeronautical_dataset_from_geojson(const char *json_utf8);

/**
 * Returns the counts of airspaces, navaids, airways, and airports in the dataset. Returns 0 on success.
 */
int olayer_aeronautical_dataset_counts(AeronauticalDataset *ds,
                                       uintptr_t *out_airspaces,
                                       uintptr_t *out_navaids,
                                       uintptr_t *out_airways,
                                       uintptr_t *out_airports);

/**
 * Finds a navaid by its identification code. Returns 0 on success, -1 on null pointer, -2 if not found.
 */
int olayer_aeronautical_dataset_find_navaid(AeronauticalDataset *ds,
                                            const char *ident_utf8,
                                            struct C_NavaidSummary *out_navaid);

/**
 * Serializes the dataset into a standard GeoJSON FeatureCollection string into a C buffer.
 * Returns 0 on success, -1 on error, or -2 if buffer capacity is insufficient.
 */
int olayer_aeronautical_dataset_to_geojson(AeronauticalDataset *ds,
                                           char *out_buf,
                                           uintptr_t out_capacity,
                                           uintptr_t *out_len);

/**
 * Destroys an `AeronauticalDataset` instance.
 */
void olayer_aeronautical_dataset_free(AeronauticalDataset *ds);

/**
 * Maps a radar reflectivity value (dBZ) to 4-byte RGBA array.
 * palette_code: 0 = Nexrad, 1 = Icao, 2 = HighContrast.
 */
int olayer_weather_dbz_to_rgba(double dbz, int palette_code, uint8_t *out_rgba);

/**
 * Generates aviation-standard wind barb line coordinates in degrees.
 * Writes flat lines `[start_lat, start_lon, end_lat, end_lon, ...]` into `out_lines`.
 */
int olayer_weather_generate_wind_barb(double origin_lat_deg,
                                      double origin_lon_deg,
                                      double speed_knots,
                                      double direction_deg,
                                      double staff_length_meters,
                                      bool is_southern_hemisphere,
                                      double *out_lines,
                                      uintptr_t max_floats,
                                      uintptr_t *out_count);

/**
 * Generates Marching Squares 2D isolines from a scalar grid.
 * Writes flat segments `[isovalue, start_lat_deg, start_lon_deg, end_lat_deg, end_lon_deg, ...]` into `out_segments`.
 */
int olayer_weather_generate_isolines(const double *grid,
                                     uintptr_t width,
                                     uintptr_t height,
                                     double min_lat_deg,
                                     double min_lon_deg,
                                     double max_lat_deg,
                                     double max_lon_deg,
                                     const double *isovalues,
                                     uintptr_t isovalues_count,
                                     double *out_segments,
                                     uintptr_t max_floats,
                                     uintptr_t *out_count);

/**
 * Parses a GeoJSON string into a heap-allocated `SigmetDataset`.
 */
SigmetDataset *olayer_sigmet_dataset_from_geojson(const char *geojson_str);

/**
 * Returns the total number of warnings in a `SigmetDataset`.
 */
int olayer_sigmet_dataset_total_count(const SigmetDataset *ds, uintptr_t *out_count);

/**
 * Destroys a heap-allocated `SigmetDataset`.
 */
void olayer_sigmet_dataset_free(SigmetDataset *ds);

/**
 * Generates an extruded 3D volumetric airspace mesh.
 * Writes flat interleaved vertices `[x, y, z, nx, ny, nz, height_ratio, is_edge, ...]` into `out_vertices`
 * and triangle indices into `out_indices`.
 */
int olayer_volumetric_generate_airspace_mesh(const struct C_LatLon *polygon_coords,
                                             uintptr_t polygon_len,
                                             double floor_m,
                                             double ceiling_m,
                                             float *out_vertices,
                                             uintptr_t max_vertices_floats,
                                             uintptr_t *out_vertices_count,
                                             uint32_t *out_indices,
                                             uintptr_t max_indices,
                                             uintptr_t *out_indices_count);

/**
 * Generates a continuous 3D flight trajectory ribbon mesh in ECEF coordinates.
 * Writes flat interleaved vertices `[x, y, z, nx, ny, nz, u, v, scalar, ...]` into `out_vertices`
 * and triangle indices into `out_indices`.
 */
int olayer_volumetric_generate_trajectory_ribbon(const struct C_LatLon *waypoints,
                                                 uintptr_t waypoints_len,
                                                 double ribbon_width_m,
                                                 const double *scalars,
                                                 uintptr_t scalars_len,
                                                 float *out_vertices,
                                                 uintptr_t max_vertices_floats,
                                                 uintptr_t *out_vertices_count,
                                                 uint32_t *out_indices,
                                                 uintptr_t max_indices,
                                                 uintptr_t *out_indices_count);

#endif /* OLAYER_NATIVE_H */
