#ifndef OLAYER_NATIVE_H
#define OLAYER_NATIVE_H

/* Automatically generated by cbindgen. Do not modify manually. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>
typedef struct TerrainEngine TerrainEngine;
typedef struct InterpolationEngine InterpolationEngine;

/**
 * C representation of vertical profile point.
 */
struct C_ProfilePoint {
  double distance_meters;
  double ground_elevation;
  double lat;
  double lon;
  double height;
};

/**
 * C representation of interpolated target.
 */
struct C_InterpolatedTarget {
  char *id;
  double lat;
  double lon;
  double height;
  double heading_rad;
};

/**
 * Creates a new TerrainEngine instance and returns an opaque pointer.
 */
TerrainEngine *olayer_terrain_engine_create(void);

/**
 * Parses and registers a raw DTED buffer.
 * Returns 0 on success, or a negative code on error.
 */
int olayer_terrain_engine_load_tile(TerrainEngine *engine,
                                    const uint8_t *data,
                                    uintptr_t length,
                                    int32_t *out_lat_deg,
                                    int32_t *out_lon_deg);

/**
 * Unloads a terrain tile. Returns 1 if tile existed, 0 if not, or negative error.
 */
int olayer_terrain_engine_unload_tile(TerrainEngine *engine, int32_t lat_deg, int32_t lon_deg);

/**
 * Resolves elevation at coordinate degrees. Returns 0 on success, negative error.
 */
int olayer_terrain_engine_get_elevation(TerrainEngine *engine,
                                        double lat_deg,
                                        double lon_deg,
                                        double *out_elevation);

/**
 * Resolves elevation at coordinate radians. Returns 0 on success, negative error.
 */
int olayer_terrain_engine_get_elevation_rad(TerrainEngine *engine,
                                            double lat_rad,
                                            double lon_rad,
                                            double *out_elevation);

/**
 * Generates a vertical profile. Fills out_profile and out_count.
 * Returns 0 on success, negative error.
 */
int olayer_terrain_engine_get_vertical_profile(TerrainEngine *engine,
                                               const double *route_lat,
                                               const double *route_lon,
                                               const double *route_height,
                                               uintptr_t route_len,
                                               double step_meters,
                                               struct C_ProfilePoint **out_profile,
                                               uintptr_t *out_count);

/**
 * Frees profile point array allocated by Rust.
 */
void olayer_profile_points_free(struct C_ProfilePoint *points, uintptr_t count);

/**
 * Sets the terrain tile cache capacity. Returns 0 on success, negative error.
 */
int olayer_terrain_engine_set_cache_capacity(TerrainEngine *engine, uintptr_t capacity);

/**
 * Returns the current number of cached terrain tiles.
 */
uintptr_t olayer_terrain_engine_cache_size(TerrainEngine *engine);

/**
 * Clears all cached terrain tiles.
 */
void olayer_terrain_engine_clear_cache(TerrainEngine *engine);

/**
 * Destroys a TerrainEngine instance.
 */
void olayer_terrain_engine_free(TerrainEngine *engine);

/**
 * Creates a new InterpolationEngine instance.
 */
InterpolationEngine *olayer_interpolator_create(void);

/**
 * Creates a new InterpolationEngine instance with custom stale threshold.
 */
InterpolationEngine *olayer_interpolator_create_with_threshold(double stale_threshold);

/**
 * Updates or inserts a target state. Returns 0 on success, negative error.
 */
int olayer_interpolator_update(InterpolationEngine *engine,
                               const char *id,
                               double lat,
                               double lon,
                               double height,
                               double speed_mps,
                               double track_heading_rad,
                               double vertical_rate_mps,
                               double time);

/**
 * Removes a target. Returns 1 if present, 0 if not, or negative error.
 */
int olayer_interpolator_remove(InterpolationEngine *engine, const char *id);

/**
 * Interpolates all targets. Fills out_targets and out_count.
 * Returns 0 on success, negative error.
 */
int olayer_interpolator_interpolate_all(InterpolationEngine *engine,
                                        double current_time,
                                        struct C_InterpolatedTarget **out_targets,
                                        uintptr_t *out_count);

/**
 * Frees interpolated targets allocated by Rust.
 */
void olayer_interpolated_targets_free(struct C_InterpolatedTarget *targets, uintptr_t count);

/**
 * Destroys an InterpolationEngine instance.
 */
void olayer_interpolator_free(InterpolationEngine *engine);

#endif /* OLAYER_NATIVE_H */
