#ifndef OLAYER_NATIVE_H
#define OLAYER_NATIVE_H

/* Automatically generated by cbindgen. Do not modify manually. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>
typedef struct TerrainEngine TerrainEngine;
typedef struct InterpolationEngine InterpolationEngine;
typedef struct LocalTangentFrame LocalTangentFrame;
typedef struct MagneticModel MagneticModel;
typedef struct AeronauticalDataset AeronauticalDataset;
typedef struct SigmetDataset SigmetDataset;

/**
 * Conversion constant: 1 Nautical Mile in meters (exact standard).
 */
#define METERS_PER_NAUTICAL_MILE 1852.0

/**
 * Standard Rate-One turn rate in degrees per second ($3^\circ/\text{s}$, $180^\circ$ in 1 minute).
 */
#define STANDARD_RATE_ONE_TURN_DPS 3.0

/**
 * Maximum generated samples along each half-turn of a holding pattern.
 */
#define MAX_HOLDING_PATTERN_POINTS_PER_TURN 512

/**
 * Maximum number of arc intervals in an ILS funnel.
 */
#define MAX_ILS_ARC_STEPS 512

/**
 * Maximum number of distance ticks in an ILS centerline.
 */
#define MAX_ILS_TICK_MARKS 256

/**
 * Maximum number of range rings generated in one request.
 */
#define MAX_RANGE_RINGS 64

/**
 * Maximum sample intervals generated for each range ring.
 */
#define MAX_RANGE_RING_POINTS 720

/**
 * C representation of vertical profile point.
 */
struct C_ProfilePoint {
  double distance_meters;
  double ground_elevation;
  double lat;
  double lon;
  double height;
};

/**
 * C representation of interpolated target.
 */
struct C_InterpolatedTarget {
  char *id;
  double lat;
  double lon;
  double height;
  double heading_rad;
  int quality;
};

/**
 * C representation of topocentric East-North-Up coordinate.
 */
struct C_EnuPoint {
  double east_m;
  double north_m;
  double up_m;
};

/**
 * C representation of geodetic coordinate.
 */
struct C_LatLon {
  double lat;
  double lon;
  double height;
};

/**
 * C representation of magnetic field elements.
 */
struct C_MagneticElements {
  double declination_rad;
  double inclination_rad;
  double horizontal_intensity_nt;
  double total_intensity_nt;
  double x_nt;
  double y_nt;
  double z_nt;
};

/**
 * C representation of route deviation metrics (XTK / ATD).
 */
struct C_RouteDeviation {
  double cross_track_error_meters;
  double along_track_distance_meters;
  struct C_LatLon nearest_point;
};

/**
 * C representation of Range and Bearing Line (RBL / CRSR) measurement.
 */
struct C_RblMeasurement {
  double from_lat_deg;
  double from_lon_deg;
  double to_lat_deg;
  double to_lon_deg;
  double distance_nm;
  double distance_km;
  double true_bearing_deg;
  double magnetic_bearing_deg;
  double reciprocal_true_bearing_deg;
  double reciprocal_magnetic_bearing_deg;
  double estimated_time_enroute_sec;
};

/**
 * C representation of a Projected Position Leader (PPL) tick mark.
 */
struct C_PplTick {
  double time_minutes;
  double distance_nm;
  double lat_deg;
  double lon_deg;
};

/**
 * C representation of a radio navigation aid summary.
 */
struct C_NavaidSummary {
  double lat;
  double lon;
  double elevation_m;
  double frequency_mhz;
  int navaid_type_code;
};

/**
 * C-compatible target descriptor for label deconfliction.
 */
struct C_LabelTarget {
  float x;
  float y;
  float heading_rad;
  float width;
  float height;
  uint8_t priority;
};

/**
 * C-compatible solved placement for a label.
 */
struct C_LabelPlacement {
  float rect_x;
  float rect_y;
  float rect_width;
  float rect_height;
  float leader_start_x;
  float leader_start_y;
  float leader_end_x;
  float leader_end_y;
  uint8_t octant;
  float cost;
};

/**
 * Creates a new TerrainEngine instance and returns an opaque pointer.
 */
TerrainEngine *olayer_terrain_engine_create(void);

/**
 * Parses and registers a raw DTED buffer.
 * Returns 0 on success, or a negative code on error.
 *
 * # Safety
 * `engine` must be a live exclusive handle from `olayer_terrain_engine_create`.
 * `data` must be aligned and readable for `length` bytes; the byte range must
 * not exceed `isize::MAX` and must not overlap the engine or output locations.
 * Each non-null output pointer must be aligned, writable for one `i32`, and
 * disjoint from every other referenced range for the duration of the call.
 */
int olayer_terrain_engine_load_tile(TerrainEngine *engine,
                                    const uint8_t *data,
                                    uintptr_t length,
                                    int32_t *out_lat_deg,
                                    int32_t *out_lon_deg);

/**
 * Unloads a terrain tile. Returns 1 if tile existed, 0 if not, or negative error.
 *
 * # Safety
 * `engine` must be a live exclusive handle returned by
 * `olayer_terrain_engine_create`, not freed or concurrently accessed.
 */
int olayer_terrain_engine_unload_tile(TerrainEngine *engine, int32_t lat_deg, int32_t lon_deg);

/**
 * Loads and registers a Web Mercator (Z, X, Y) RGB elevation tile.
 * encoding_code: 0 = MapboxRgb, 1 = Terrarium.
 * Returns 0 on success, or a negative code on error.
 *
 * # Safety
 * `engine` must be a live shared handle returned by
 * `olayer_terrain_engine_create`. `rgba_data` must be aligned and readable for
 * `rgba_len` bytes (no more than `isize::MAX`), and must not overlap `engine`.
 */
int olayer_terrain_engine_load_rgb_tile(TerrainEngine *engine,
                                        uint32_t z,
                                        uint32_t x,
                                        uint32_t y,
                                        int encoding_code,
                                        const uint8_t *rgba_data,
                                        uintptr_t rgba_len,
                                        uintptr_t width,
                                        uintptr_t height);

/**
 * Loads a GeoTIFF / Cloud-Optimized GeoTIFF raster.
 * Returns 0 on success, or negative error.
 *
 * # Safety
 * `engine` must be a live shared handle returned by
 * `olayer_terrain_engine_create`. `data` must be aligned and readable for
 * `length` bytes, with a range no larger than `isize::MAX`. Every non-null
 * output must be aligned and writable for one `f64`; outputs must not overlap
 * the input or one another.
 */
int olayer_terrain_engine_load_geotiff(TerrainEngine *engine,
                                       const uint8_t *data,
                                       uintptr_t length,
                                       double *out_min_lat_deg,
                                       double *out_min_lon_deg,
                                       double *out_max_lat_deg,
                                       double *out_max_lon_deg);

/**
 * Decodes Mapbox Terrain-RGB pixel value to elevation in meters.
 *
 * # Safety
 * `out_elevation` must be non-null, aligned, and writable for one `f64`.
 */
int olayer_terrain_decode_mapbox_rgb(uint8_t r, uint8_t g, uint8_t b, double *out_elevation);

/**
 * Decodes Mapzen / Nextzen Terrarium RGB pixel value to elevation in meters.
 *
 * # Safety
 * `out_elevation` must be non-null, aligned, and writable for one `f64`.
 */
int olayer_terrain_decode_terrarium_rgb(uint8_t r, uint8_t g, uint8_t b, double *out_elevation);

/**
 * Resolves elevation at coordinate degrees. Returns 0 on success, negative error.
 *
 * # Safety
 * `engine` must be a live exclusive handle from `olayer_terrain_engine_create`.
 * `out_elevation` must be non-null, aligned, writable for one `f64`, and must
 * not alias the engine.
 */
int olayer_terrain_engine_get_elevation(TerrainEngine *engine,
                                        double lat_deg,
                                        double lon_deg,
                                        double *out_elevation);

/**
 * Resolves elevation at coordinate radians. Returns 0 on success, negative error.
 *
 * # Safety
 * `engine` must be a live exclusive handle from `olayer_terrain_engine_create`.
 * `out_elevation` must be non-null, aligned, writable for one `f64`, and must
 * not alias the engine.
 */
int olayer_terrain_engine_get_elevation_rad(TerrainEngine *engine,
                                            double lat_rad,
                                            double lon_rad,
                                            double *out_elevation);

/**
 * Resolves elevation at radians while preserving DTED null samples.
 * Returns 0 for valid data, 1 for unknown elevation, or a negative error.
 *
 * # Safety
 * `engine` must be a live exclusive handle from `olayer_terrain_engine_create`.
 * `out_elevation` must be non-null, aligned, writable for one `f64`, and must
 * not alias the engine.
 */
int olayer_terrain_engine_get_elevation_status(TerrainEngine *engine,
                                               double lat_rad,
                                               double lon_rad,
                                               double *out_elevation);

/**
 * Resolves an object height against terrain.
 * `mode`: 0 absolute, 1 clamp-to-ground, 2 relative-to-ground, 3 relative-to-mesh.
 * `unknown_policy`: 0 reject, 1 use-absolute, 2 use-zero.
 *
 * # Safety
 * `engine` must be a live exclusive handle from `olayer_terrain_engine_create`.
 * `out_height` must be non-null, aligned, writable for one `f64`, and must not
 * alias the engine.
 */
int olayer_terrain_engine_resolve_altitude(TerrainEngine *engine,
                                           double lat_rad,
                                           double lon_rad,
                                           double input_height,
                                           int mode,
                                           int unknown_policy,
                                           double mesh_height,
                                           double *out_height);

/**
 * Computes MSAW clearance. Returns 0 safe, 1 warning, 2 unknown terrain, or a negative error.
 *
 * # Safety
 * `engine` must be a live exclusive handle from `olayer_terrain_engine_create`.
 * `out_clearance` must be non-null, aligned, writable for one `f64`, and must
 * not alias the engine.
 */
int olayer_terrain_engine_calculate_clearance(TerrainEngine *engine,
                                              double lat_rad,
                                              double lon_rad,
                                              double aircraft_height_meters,
                                              double minimum_clearance_meters,
                                              bool reject_unknown,
                                              double *out_clearance);

/**
 * Generates a vertical profile. Fills out_profile and out_count.
 * Returns 0 on success, -1 for invalid or over-budget inputs, -2 for terrain
 * or route failures, and -99 if a panic is caught.
 *
 * # Safety
 * The three route pointers must each be aligned and readable for `route_len`
 * initialized `f64` values; their ranges must not overlap each other. `engine`
 * must be a live exclusive handle from `olayer_terrain_engine_create`. Both
 * output pointers must be aligned, writable, and disjoint from the inputs and
 * each other (`out_profile` for one pointer and `out_count` for one `usize`).
 * On success, release the returned array once with its exact count using
 * `olayer_profile_points_free`.
 */
int olayer_terrain_engine_get_vertical_profile(TerrainEngine *engine,
                                               const double *route_lat,
                                               const double *route_lon,
                                               const double *route_height,
                                               uintptr_t route_len,
                                               double step_meters,
                                               struct C_ProfilePoint **out_profile,
                                               uintptr_t *out_count);

/**
 * Frees profile point array allocated by Rust.
 *
 * # Safety
 * `points` must be null or the exact pointer returned by a successful
 * `olayer_terrain_engine_get_vertical_profile`; `count` must be its exact
 * element count. A non-null pointer must be aligned and freed exactly once.
 */
void olayer_profile_points_free(struct C_ProfilePoint *points, uintptr_t count);

/**
 * Sets the terrain tile cache capacity. Returns 0 on success, negative error.
 *
 * # Safety
 * `engine` must be a live exclusive handle returned by
 * `olayer_terrain_engine_create`, not freed or concurrently accessed.
 */
int olayer_terrain_engine_set_cache_capacity(TerrainEngine *engine, uintptr_t capacity);

/**
 * Returns the current number of cached terrain tiles.
 *
 * # Safety
 * A non-null `engine` must be a live handle returned by
 * `olayer_terrain_engine_create` and must not be concurrently mutated or freed.
 */
uintptr_t olayer_terrain_engine_cache_size(TerrainEngine *engine);

/**
 * Clears all cached terrain tiles.
 *
 * # Safety
 * A non-null `engine` must be a live exclusive handle returned by
 * `olayer_terrain_engine_create`, not freed or concurrently accessed.
 */
void olayer_terrain_engine_clear_cache(TerrainEngine *engine);

/**
 * Destroys a TerrainEngine instance.
 *
 * # Safety
 * `engine` must be null or the unique, still-live pointer returned by
 * `olayer_terrain_engine_create`; it must not have been freed or be in use.
 */
void olayer_terrain_engine_free(TerrainEngine *engine);

/**
 * Creates a new InterpolationEngine instance.
 */
InterpolationEngine *olayer_interpolator_create(void);

/**
 * Creates a new InterpolationEngine instance with custom stale threshold.
 */
InterpolationEngine *olayer_interpolator_create_with_threshold(double stale_threshold);

/**
 * Updates or inserts a target state. Returns 0 on success, negative error.
 *
 * # Safety
 * `engine` must be a live exclusive handle returned by an interpolator
 * constructor. `id` must point to a readable, aligned, NUL-terminated byte
 * string of at most `MAX_TARGET_ID_BYTES` bytes whose bytes remain valid for
 * this call and do not overlap the engine.
 */
int olayer_interpolator_update(InterpolationEngine *engine,
                               const char *id,
                               double lat,
                               double lon,
                               double height,
                               double speed_mps,
                               double track_heading_rad,
                               double vertical_rate_mps,
                               double time);

/**
 * Removes a target. Returns 1 if present, 0 if not, or negative error.
 *
 * # Safety
 * `engine` must be a live exclusive handle returned by an interpolator
 * constructor. `id` must point to a readable, aligned, NUL-terminated byte
 * string of at most `MAX_TARGET_ID_BYTES` bytes whose bytes remain valid for
 * this call and do not overlap the engine.
 */
int olayer_interpolator_remove(InterpolationEngine *engine, const char *id);

/**
 * Interpolates all targets. Fills out_targets and out_count.
 * Returns 0 on success, negative error.
 *
 * # Safety
 * `engine` must be a live exclusive handle returned by an interpolator
 * constructor. Both output pointers must be aligned, writable for one value,
 * and disjoint from each other and the engine. On success, release the returned
 * array once with its exact count using `olayer_interpolated_targets_free`.
 */
int olayer_interpolator_interpolate_all(InterpolationEngine *engine,
                                        double current_time,
                                        struct C_InterpolatedTarget **out_targets,
                                        uintptr_t *out_count);

/**
 * Frees interpolated targets allocated by Rust.
 *
 * # Safety
 * `targets` must be null or the exact pointer returned by a successful
 * `olayer_interpolator_interpolate_all`; `count` must be its exact element
 * count. Each non-null ID must still be the original returned CString pointer.
 * The array and each ID must be freed exactly once and must not have been altered.
 */
void olayer_interpolated_targets_free(struct C_InterpolatedTarget *targets, uintptr_t count);

/**
 * Destroys an InterpolationEngine instance.
 *
 * # Safety
 * `engine` must be null or the unique, still-live pointer returned by an
 * interpolator constructor; it must not have been freed or be in use.
 */
void olayer_interpolator_free(InterpolationEngine *engine);

/**
 * Creates a new `LocalTangentFrame` at the given geodetic origin.
 */
LocalTangentFrame *olayer_local_frame_create(double origin_lat,
                                             double origin_lon,
                                             double origin_height);

/**
 * Converts LLA to local ENU coordinates. Returns 0 on success, negative error.
 *
 * # Safety
 * `frame` must be a live handle returned by `olayer_local_frame_create`.
 * `out_enu` must be aligned and writable for one `C_EnuPoint`, and must not
 * overlap the frame.
 */
int olayer_local_frame_lla_to_enu(LocalTangentFrame *frame,
                                  double lat,
                                  double lon,
                                  double height,
                                  struct C_EnuPoint *out_enu);

/**
 * Converts local ENU coordinates to LLA. Returns 0 on success, negative error.
 *
 * # Safety
 * `frame` must be a live handle returned by `olayer_local_frame_create`.
 * `out_lla` must be aligned and writable for one `C_LatLon`, and must not
 * overlap the frame.
 */
int olayer_local_frame_enu_to_lla(LocalTangentFrame *frame,
                                  double east_m,
                                  double north_m,
                                  double up_m,
                                  struct C_LatLon *out_lla);

/**
 * Calculates radar look angles without atmospheric refraction. Returns 0 on success, negative error.
 *
 * # Safety
 * `frame` must be a live handle returned by `olayer_local_frame_create`. Each
 * output pointer must be aligned and writable for one `f64`; they must be
 * mutually disjoint and must not overlap the frame.
 */
int olayer_local_frame_radar_look_angles(LocalTangentFrame *frame,
                                         double target_lat,
                                         double target_lon,
                                         double target_height,
                                         double *out_slant_range,
                                         double *out_azimuth_rad,
                                         double *out_elevation_rad);

/**
 * Calculates radar look angles with 4/3 tropospheric refraction. Returns 0 on success, negative error.
 *
 * # Safety
 * `frame` must be a live handle returned by `olayer_local_frame_create`. Each
 * output pointer must be aligned and writable for one `f64`; they must be
 * mutually disjoint and must not overlap the frame.
 */
int olayer_local_frame_radar_look_angles_refracted(LocalTangentFrame *frame,
                                                   double target_lat,
                                                   double target_lon,
                                                   double target_height,
                                                   double k_factor,
                                                   double *out_slant_range,
                                                   double *out_azimuth_rad,
                                                   double *out_elevation_rad);

/**
 * Destroys a `LocalTangentFrame` instance.
 *
 * # Safety
 * `frame` must be null or the unique, still-live pointer returned by
 * `olayer_local_frame_create`; it must not have been freed or be in use.
 */
void olayer_local_frame_free(LocalTangentFrame *frame);

/**
 * Creates a default `MagneticModel` instance initialized with built-in WMM-2025.
 */
MagneticModel *olayer_magnetic_model_create_default(void);

/**
 * Creates a `MagneticModel` from a null-terminated `WMM.COF` string.
 * Returns null pointer if parsing fails or string is invalid UTF-8.
 *
 * # Safety
 * `cof_str` must be null or point to an aligned, readable, NUL-terminated byte
 * string no longer than `MAX_FFI_TEXT_BYTES` bytes that remains valid for this
 * call.
 */
MagneticModel *olayer_magnetic_model_create_from_cof(const char *cof_str);

/**
 * Computes magnetic declination using a specific `MagneticModel` instance.
 *
 * # Safety
 * `model` must be a live handle returned by a magnetic-model constructor.
 * `out_declination_rad` must be aligned and writable for one `f64`, without
 * overlapping the model.
 */
int olayer_magnetic_model_get_declination(MagneticModel *model,
                                          double lat,
                                          double lon,
                                          double height,
                                          double epoch,
                                          double *out_declination_rad);

/**
 * Computes magnetic field elements using a specific `MagneticModel` instance.
 *
 * # Safety
 * `model` must be a live handle returned by a magnetic-model constructor.
 * `out_elements` must be aligned and writable for one `C_MagneticElements`,
 * without overlapping the model.
 */
int olayer_magnetic_model_get_elements(MagneticModel *model,
                                       double lat,
                                       double lon,
                                       double height,
                                       double epoch,
                                       struct C_MagneticElements *out_elements);

/**
 * Converts True bearing to Magnetic bearing using a specific `MagneticModel` instance.
 *
 * # Safety
 * `model` must be a live handle returned by a magnetic-model constructor.
 * `out_mag_bearing_rad` must be aligned and writable for one `f64`, without
 * overlapping the model.
 */
int olayer_magnetic_model_true_to_magnetic(MagneticModel *model,
                                           double true_bearing_rad,
                                           double lat,
                                           double lon,
                                           double height,
                                           double epoch,
                                           double *out_mag_bearing_rad);

/**
 * Converts Magnetic bearing to True bearing using a specific `MagneticModel` instance.
 *
 * # Safety
 * `model` must be a live handle returned by a magnetic-model constructor.
 * `out_true_bearing_rad` must be aligned and writable for one `f64`, without
 * overlapping the model.
 */
int olayer_magnetic_model_magnetic_to_true(MagneticModel *model,
                                           double mag_bearing_rad,
                                           double lat,
                                           double lon,
                                           double height,
                                           double epoch,
                                           double *out_true_bearing_rad);

/**
 * Destroys a `MagneticModel` instance.
 *
 * # Safety
 * `model` must be null or the unique, still-live pointer returned by a
 * magnetic-model constructor; it must not have been freed or be in use.
 */
void olayer_magnetic_model_free(MagneticModel *model);

/**
 * Computes magnetic declination in radians using default WMM-2025. Returns 0 on success, negative error.
 *
 * # Safety
 * `out_declination_rad` must be non-null, aligned, and writable for one `f64`.
 */
int olayer_magnetic_get_declination(double lat,
                                    double lon,
                                    double height,
                                    double epoch,
                                    double *out_declination_rad);

/**
 * Computes all magnetic field elements using default WMM-2025. Returns 0 on success, negative error.
 *
 * # Safety
 * `out_elements` must be non-null, aligned, and writable for one `C_MagneticElements`.
 */
int olayer_magnetic_get_elements(double lat,
                                 double lon,
                                 double height,
                                 double epoch,
                                 struct C_MagneticElements *out_elements);

/**
 * Converts True bearing to Magnetic bearing using default WMM-2025. Returns 0 on success, negative error.
 *
 * # Safety
 * `out_mag_bearing_rad` must be non-null, aligned, and writable for one `f64`.
 */
int olayer_magnetic_true_to_magnetic(double true_bearing_rad,
                                     double lat,
                                     double lon,
                                     double height,
                                     double epoch,
                                     double *out_mag_bearing_rad);

/**
 * Converts Magnetic bearing to True bearing using default WMM-2025. Returns 0 on success, negative error.
 *
 * # Safety
 * `out_true_bearing_rad` must be non-null, aligned, and writable for one `f64`.
 */
int olayer_magnetic_magnetic_to_true(double mag_bearing_rad,
                                     double lat,
                                     double lon,
                                     double height,
                                     double epoch,
                                     double *out_true_bearing_rad);

/**
 * Computes route deviation (XTK and ATD). Returns 0 on success, negative error.
 *
 * # Safety
 * `out_deviation` must be non-null, aligned, and writable for one
 * `C_RouteDeviation`.
 */
int olayer_spatial_compute_route_deviation(struct C_LatLon start,
                                           struct C_LatLon end,
                                           struct C_LatLon pos,
                                           struct C_RouteDeviation *out_deviation);

/**
 * Computes geodesic line-line intersection. Returns 1 if intersects, 0 if disjoint, negative error.
 *
 * # Safety
 * `out_intersection` must be non-null, aligned, and writable for one `C_LatLon`.
 */
int olayer_spatial_geodesic_intersection(struct C_LatLon p1,
                                         struct C_LatLon p2,
                                         struct C_LatLon p3,
                                         struct C_LatLon p4,
                                         struct C_LatLon *out_intersection);

/**
 * Evaluates spherical polygon point containment. Returns 0 on success, negative error.
 * `*out_contains` is set to 1 if contained, 0 if not.
 *
 * # Safety
 * `poly_coords` must be aligned and readable for `num_coords` initialized
 * `C_LatLon` elements; that range must not exceed `isize::MAX` bytes.
 * `out_contains` must be aligned and writable for one `c_int`; it must not
 * overlap the coordinate array.
 */
int olayer_spatial_polygon_contains_point(const struct C_LatLon *poly_coords,
                                          uintptr_t num_coords,
                                          struct C_LatLon point,
                                          int *out_contains);

/**
 * Computes Range and Bearing Line (RBL / CRSR) measurement. Returns 0 on success, negative error.
 *
 * # Safety
 * `out_measurement` must be non-null, aligned, and writable for one
 * `C_RblMeasurement`.
 */
int olayer_tools_compute_rbl(double from_lat_deg,
                             double from_lon_deg,
                             double to_lat_deg,
                             double to_lon_deg,
                             double speed_knots,
                             double epoch_year,
                             struct C_RblMeasurement *out_measurement);

/**
 * Generates Projected Position Leader (PPL) vector ticks. Returns 0 on success,
 * -1 for invalid pointers or empty intervals, and -2 if `num_intervals` exceeds
 * the configured input limit.
 *
 * # Safety
 * `intervals_minutes` must be aligned and readable for `num_intervals`
 * initialized `f64` values; the range must not exceed `isize::MAX` bytes.
 * `out_ticks` must be aligned and writable for `max_ticks` `C_PplTick`
 * elements, and `out_ticks_written` aligned/writable for one `usize`; output
 * ranges must be disjoint from the input and each other.
 */
int olayer_tools_generate_ppl(double lat_deg,
                              double lon_deg,
                              double ground_speed_knots,
                              double track_deg,
                              const double *intervals_minutes,
                              uintptr_t num_intervals,
                              struct C_PplTick *out_ticks,
                              uintptr_t max_ticks,
                              uintptr_t *out_ticks_written);

/**
 * Generates racetrack holding pattern polyline coordinates. Returns 0 on
 * success, -1 for invalid pointers, and -2 if `points_per_turn` exceeds its
 * configured generation limit.
 *
 * # Safety
 * `out_coords` must be aligned and writable for `max_coords` `C_LatLon`
 * elements; `out_coords_written` must be aligned and writable for one `usize`.
 * These ranges must not overlap. `max_coords` must describe the actual output
 * allocation, even when smaller than the generated result.
 */
int olayer_tools_generate_holding_pattern(double fix_lat_deg,
                                          double fix_lon_deg,
                                          double inbound_bearing_deg,
                                          int is_standard_right_turn,
                                          double leg_time_minutes,
                                          double airspeed_knots,
                                          uintptr_t points_per_turn,
                                          struct C_LatLon *out_coords,
                                          uintptr_t max_coords,
                                          uintptr_t *out_coords_written);

/**
 * Generates ILS approach funnel polygon coordinates. Returns 0 on success,
 * -1 for invalid pointers, and -2 if `arc_steps` exceeds its configured limit.
 *
 * # Safety
 * `out_polygon_coords` must be aligned and writable for `max_polygon_coords`
 * `C_LatLon` elements; `out_polygon_coords_written` must be aligned and
 * writable for one `usize`. The ranges must not overlap.
 */
int olayer_tools_generate_ils_cone(double threshold_lat_deg,
                                   double threshold_lon_deg,
                                   double runway_heading_deg,
                                   double length_nm,
                                   double fov_deg,
                                   uintptr_t arc_steps,
                                   struct C_LatLon *out_polygon_coords,
                                   uintptr_t max_polygon_coords,
                                   uintptr_t *out_polygon_coords_written);

/**
 * Generates concentric range rings coordinates. Returns 0 on success, -1 for
 * invalid pointers, and -2 if `points_per_ring` exceeds its configured limit.
 *
 * # Safety
 * `out_ring_coords` must be aligned and writable for `max_coords` `C_LatLon`
 * elements; `out_coords_written` must be aligned and writable for one `usize`.
 * The ranges must not overlap.
 */
int olayer_tools_generate_range_rings(double center_lat_deg,
                                      double center_lon_deg,
                                      double radius_nm,
                                      uintptr_t points_per_ring,
                                      struct C_LatLon *out_ring_coords,
                                      uintptr_t max_coords,
                                      uintptr_t *out_coords_written);

/**
 * Loads an `AeronauticalDataset` from an AIXM 5.1 XML null-terminated UTF-8 string.
 * Returns null pointer on error.
 *
 * # Safety
 * `xml_utf8` must be null or point to readable, aligned, NUL-terminated bytes
 * valid for this call. The complete string must be no longer than
 * `MAX_FFI_TEXT_BYTES` bytes, excluding its terminator.
 */
AeronauticalDataset *olayer_aeronautical_dataset_from_aixm(const char *xml_utf8);

/**
 * Loads an `AeronauticalDataset` from a GeoJSON-Aviation null-terminated UTF-8 string.
 * Returns null pointer on error.
 *
 * # Safety
 * `json_utf8` must be null or point to readable, aligned, NUL-terminated bytes
 * valid for this call. The complete string must be no longer than
 * `MAX_FFI_TEXT_BYTES` bytes, excluding its terminator.
 */
AeronauticalDataset *olayer_aeronautical_dataset_from_geojson(const char *json_utf8);

/**
 * Returns the counts of airspaces, navaids, airways, and airports in the dataset. Returns 0 on success.
 *
 * # Safety
 * `ds` must be a live handle returned by an aeronautical dataset constructor.
 * Each non-null output must be aligned and writable for one `usize`; output
 * pointers must not overlap one another or the dataset.
 */
int olayer_aeronautical_dataset_counts(AeronauticalDataset *ds,
                                       uintptr_t *out_airspaces,
                                       uintptr_t *out_navaids,
                                       uintptr_t *out_airways,
                                       uintptr_t *out_airports);

/**
 * Finds a navaid by its identification code. Returns 0 on success, -1 on null pointer, -2 if not found.
 *
 * # Safety
 * `ds` must be a live dataset handle. `ident_utf8` must point to readable,
 * aligned, NUL-terminated bytes of at most `MAX_TARGET_ID_BYTES` valid for
 * this call. `out_navaid` must be aligned and writable for one
 * `C_NavaidSummary`, disjoint from both inputs.
 */
int olayer_aeronautical_dataset_find_navaid(AeronauticalDataset *ds,
                                            const char *ident_utf8,
                                            struct C_NavaidSummary *out_navaid);

/**
 * Serializes the dataset into a standard GeoJSON FeatureCollection string into a C buffer.
 * Returns 0 on success, -1 on error, or -2 if buffer capacity is insufficient.
 *
 * # Safety
 * `ds` must be a live dataset handle. `out_len` must be aligned and writable
 * for one `usize`. If `out_buf` is non-null, it must be aligned and writable
 * for `out_capacity` bytes; its range must not overlap the dataset or `out_len`.
 */
int olayer_aeronautical_dataset_to_geojson(AeronauticalDataset *ds,
                                           char *out_buf,
                                           uintptr_t out_capacity,
                                           uintptr_t *out_len);

/**
 * Destroys an `AeronauticalDataset` instance.
 *
 * # Safety
 * `ds` must be null or the unique, still-live pointer returned by an
 * aeronautical dataset constructor; it must not have been freed or be in use.
 */
void olayer_aeronautical_dataset_free(AeronauticalDataset *ds);

/**
 * Maps a radar reflectivity value (dBZ) to 4-byte RGBA array.
 * palette_code: 0 = Nexrad, 1 = Icao, 2 = HighContrast.
 *
 * # Safety
 * `out_rgba` must be non-null, aligned, and writable for four initialized
 * `u8` slots.
 */
int olayer_weather_dbz_to_rgba(double dbz, int palette_code, uint8_t *out_rgba);

/**
 * Generates aviation-standard wind barb line coordinates in degrees.
 * Writes flat lines `[start_lat, start_lon, end_lat, end_lon, ...]` into `out_lines`.
 *
 * # Safety
 * `out_lines` must be non-null, aligned, and writable for `max_floats` `f64`
 * elements. `out_count` must be non-null, aligned, and writable for one
 * `usize`; the output ranges must not overlap.
 */
int olayer_weather_generate_wind_barb(double origin_lat_deg,
                                      double origin_lon_deg,
                                      double speed_knots,
                                      double direction_deg,
                                      double staff_length_meters,
                                      bool is_southern_hemisphere,
                                      double *out_lines,
                                      uintptr_t max_floats,
                                      uintptr_t *out_count);

/**
 * Generates Marching Squares 2D isolines from a scalar grid.
 * Writes flat segments `[isovalue, start_lat_deg, start_lon_deg, end_lat_deg, end_lon_deg, ...]` into `out_segments`.
 *
 * # Safety
 * `grid` must be aligned and readable for `width * height` initialized `f64`
 * values and `isovalues` for `isovalues_count` initialized `f64` values. The
 * element counts are bounded and multiplication is checked before slicing.
 * `out_segments` must be aligned and writable for `max_floats` `f64` values;
 * `out_count` must be aligned and writable for one `usize`. The input and
 * output ranges must be pairwise disjoint.
 */
int olayer_weather_generate_isolines(const double *grid,
                                     uintptr_t width,
                                     uintptr_t height,
                                     double min_lat_deg,
                                     double min_lon_deg,
                                     double max_lat_deg,
                                     double max_lon_deg,
                                     const double *isovalues,
                                     uintptr_t isovalues_count,
                                     double *out_segments,
                                     uintptr_t max_floats,
                                     uintptr_t *out_count);

/**
 * Parses a GeoJSON string into a heap-allocated `SigmetDataset`.
 *
 * # Safety
 * `geojson_str` must be null or point to readable, aligned, NUL-terminated
 * bytes valid for this call and no longer than `MAX_FFI_TEXT_BYTES` bytes.
 */
SigmetDataset *olayer_sigmet_dataset_from_geojson(const char *geojson_str);

/**
 * Returns the total number of warnings in a `SigmetDataset`.
 *
 * # Safety
 * `ds` must be a live dataset handle returned by
 * `olayer_sigmet_dataset_from_geojson`. `out_count` must be aligned, writable
 * for one `usize`, and disjoint from the dataset.
 */
int olayer_sigmet_dataset_total_count(const SigmetDataset *ds, uintptr_t *out_count);

/**
 * Destroys a heap-allocated `SigmetDataset`.
 *
 * # Safety
 * `ds` must be null or the unique, still-live pointer returned by
 * `olayer_sigmet_dataset_from_geojson`; it must not have been freed or be in use.
 */
void olayer_sigmet_dataset_free(SigmetDataset *ds);

/**
 * Generates an extruded 3D volumetric airspace mesh.
 * Writes flat interleaved vertices `[x, y, z, nx, ny, nz, height_ratio, is_edge, ...]` into `out_vertices`
 * and triangle indices into `out_indices`.
 *
 * # Safety
 * `polygon_coords` must be aligned and readable for `polygon_len` initialized
 * `C_LatLon` values. `out_vertices` must be aligned and writable for
 * `max_vertices_floats` `f32` values and `out_indices` for `max_indices` `u32`
 * values. Each count output must be aligned and writable for one `usize`.
 * Input, outputs, and the two count locations must be pairwise disjoint.
 */
int olayer_volumetric_generate_airspace_mesh(const struct C_LatLon *polygon_coords,
                                             uintptr_t polygon_len,
                                             double floor_m,
                                             double ceiling_m,
                                             float *out_vertices,
                                             uintptr_t max_vertices_floats,
                                             uintptr_t *out_vertices_count,
                                             uint32_t *out_indices,
                                             uintptr_t max_indices,
                                             uintptr_t *out_indices_count);

/**
 * Generates a continuous 3D flight trajectory ribbon mesh in ECEF coordinates.
 * Writes flat interleaved vertices `[x, y, z, nx, ny, nz, u, v, scalar, ...]` into `out_vertices`
 * and triangle indices into `out_indices`.
 *
 * # Safety
 * `waypoints` must be aligned and readable for `waypoints_len` initialized
 * `C_LatLon` values. A non-null `scalars` pointer must be aligned and readable
 * for `scalars_len` initialized `f64` values. Vertex/index buffers must be
 * aligned and writable for their supplied capacities, and both count outputs
 * aligned/writable for one `usize`; all referenced ranges must be disjoint.
 */
int olayer_volumetric_generate_trajectory_ribbon(const struct C_LatLon *waypoints,
                                                 uintptr_t waypoints_len,
                                                 double ribbon_width_m,
                                                 const double *scalars,
                                                 uintptr_t scalars_len,
                                                 float *out_vertices,
                                                 uintptr_t max_vertices_floats,
                                                 uintptr_t *out_vertices_count,
                                                 uint32_t *out_indices,
                                                 uintptr_t max_indices,
                                                 uintptr_t *out_indices_count);

/**
 * Solves optimal 8-octant non-overlapping label placements for a batch of screen targets.
 *
 * # Safety
 * `targets` must be aligned and readable for `targets_len` initialized
 * `C_LabelTarget` values. `out_placements` must be aligned and writable for
 * `max_placements` placements and `out_placements_count` aligned/writable for
 * one `usize`; output ranges must not overlap each other or the input.
 */
int olayer_declutter_solve_labels(const struct C_LabelTarget *targets,
                                  uintptr_t targets_len,
                                  float leader_length_px,
                                  float safety_margin_px,
                                  struct C_LabelPlacement *out_placements,
                                  uintptr_t max_placements,
                                  uintptr_t *out_placements_count);

#endif /* OLAYER_NATIVE_H */
